allow ignore stage cmp failure

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -66051,7 +66051,11 @@ compare:
 	if [ -f .bad_compare ]; then \
 	  echo "Bootstrap comparison failure!"; \
 	  cat .bad_compare; \
-	  exit 1; \
+	  if [ -n "$$IGNORE_CMP_FAIL" ]; then \
+	    echo "Comparison failure ignored !!"; \
+	  else \
+	    exit 1; \
+	  fi; \
 	else \
 	  echo Comparison successful.; \
 	fi; \
@@ -66485,7 +66489,11 @@ compare3:
 	if [ -f .bad_compare ]; then \
 	  echo "Bootstrap comparison failure!"; \
 	  cat .bad_compare; \
-	  exit 1; \
+	  if [ -n "$$IGNORE_CMP_FAIL" ]; then \
+	    echo "Comparison failure ignored !!"; \
+	  else \
+	    exit 1; \
+	  fi; \
 	else \
 	  echo Comparison successful.; \
 	fi; \
